Review 2
denisKyandex/cpp-peer-review pull request #2
Opened 2023-11-22 21:47 UTC by denisKyandex

2023-11-23 12:44 UTC, SkopopadES requested changes

2023-11-23 12:44 UTC, SkopopadES commented on task_2.cpp
> +
// В задании было указано, что необходимо сделать юнит-тесты, чтобы убедиться, что фильтр качественный. Необходимо добавить

2023-11-23 18:45 UTC, denisKyandex commented on task_2.cpp
> +
Добавил тесты

2023-11-24 05:34 UTC, SkopopadES approved these changes
Отличная работа )

2023-11-24 14:40 UTC, merged