Review 1
denisKyandex/cpp-peer-review pull request #6
Opened 2023-11-22 22:42 UTC by denisKyandex

2023-11-23 12:26 UTC, SkopopadES requested changes

2023-11-23 12:26 UTC, SkopopadES commented on task_1.cpp
> +
//[67-80] Здесь вместо getline() лучше использовать cin

2023-11-23 12:26 UTC, SkopopadES commented on task_1.cpp
> +
//[74-75] Здесь вместо getline() лучше использовать cin

2023-11-23 12:26 UTC, SkopopadES commented on task_1.cpp
> +
// [79-90]  Здесь вместо getline() лучше использовать cin

2023-11-23 13:08 UTC, denisKyandex commented
Исправлю

2023-11-24 05:35 UTC, SkopopadES approved these changes

2023-11-24 14:40 UTC, merged